[package]
name = "blkrs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
serde_json = "1.0"

[[example]]
name = "no-modules"
path = "examples/no-modules/main.rs"

